// Copyright 2017 NDP Systèmes. All Rights Reserved.
// See LICENSE file for full licensing details.

package account

import (
	"github.com/hexya-erp/hexya-base/base"
	"github.com/hexya-erp/hexya/hexya/models/security"
	"github.com/hexya-erp/hexya/pool"
)

var (
	GroupAccountInvoice *security.Group
	GroupAccountUser    *security.Group
	GroupAccountManager *security.Group
)

func init() {
	pool.ProductProduct().Methods().Load().AllowGroup(GroupAccountUser)
	pool.ProductProduct().Methods().AllowAllToGroup(GroupAccountManager)
	pool.ProductTemplate().Methods().AllowAllToGroup(GroupAccountManager)
	pool.ProductPriceHistory().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountPaymentTerm().Methods().Load().AllowGroup(GroupAccountUser)
	pool.AccountPaymentTermLine().Methods().Load().AllowGroup(GroupAccountUser)
	pool.AccountAccountType().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountAccountType().Methods().Load().AllowGroup(GroupAccountUser)
	pool.AccountTax().Methods().Load().AllowGroup(base.GroupUser)
	pool.AccountAccount().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountAccount().Methods().Load().AllowGroup(GroupAccountUser)
	pool.AccountAccount().Methods().Load().AllowGroup(base.GroupUser)
	pool.AccountAccount().Methods().Load().AllowGroup(base.GroupPartnerManager)
	pool.AccountTax().Methods().Load().AllowGroup(GroupAccountInvoice)
	pool.AccountAccountTemplate().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountChartTemplate().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountTaxTemplate().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountBankStatement().Methods().Load().AllowGroup(GroupAccountInvoice)
	pool.AccountBankStatementLine().Methods().Load().AllowGroup(GroupAccountInvoice)
	pool.AccountBankStatement().Methods().AllowAllToGroup(GroupAccountUser)
	pool.AccountBankStatementLine().Methods().AllowAllToGroup(GroupAccountUser)
	pool.AccountAnalyticLine().Methods().Load().AllowGroup(GroupAccountManager)
	pool.AccountAnalyticAccount().Methods().Load().AllowGroup(base.GroupUser)
	pool.AccountInvoice().Methods().AllowAllToGroup(GroupAccountInvoice)
	pool.AccountInvoiceLine().Methods().AllowAllToGroup(GroupAccountInvoice)
	pool.AccountInvoiceTax().Methods().AllowAllToGroup(GroupAccountInvoice)
	pool.AccountMove().Methods().AllowAllToGroup(GroupAccountInvoice)
	pool.AccountMoveLine().Methods().AllowAllToGroup(GroupAccountInvoice)
	pool.AccountPaymentTerm().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountPaymentTermLine().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountTax().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountJournal().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountJournal().Methods().Load().AllowGroup(GroupAccountUser)
	pool.AccountJournal().Methods().Load().AllowGroup(GroupAccountInvoice)
	pool.AccountInvoice().Methods().AllowAllToGroup(GroupAccountInvoice)
	pool.Currency().Methods().AllowAllToGroup(GroupAccountManager)
	pool.CurrencyRate().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountInvoice().Methods().Load().AllowGroup(base.GroupUser)
	pool.AccountInvoiceLine().Methods().Load().AllowGroup(base.GroupUser)
	pool.AccountPaymentTerm().Methods().Load().AllowGroup(base.GroupUser)
	pool.AccountPaymentTermLine().Methods().Load().AllowGroup(base.GroupUser)
	pool.AccountFiscalPosition().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountFiscalPositionTax().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountFiscalPositionAccount().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountFiscalPosition().Methods().Load().AllowGroup(base.GroupUser)
	pool.AccountFiscalPositionTax().Methods().Load().AllowGroup(base.GroupUser)
	pool.AccountFiscalPositionAccount().Methods().Load().AllowGroup(base.GroupUser)
	pool.AccountFiscalPositionTemplate().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountFiscalPositionTaxTemplate().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountFiscalPositionAccountTemplate().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountInvoiceReport().Methods().Load().AllowGroup(GroupAccountUser)
	pool.AccountInvoiceReport().Methods().AllowAllToGroup(GroupAccountManager)
	pool.AccountInvoiceReport().Methods().Load().AllowGroup(GroupAccountInvoice)
	pool.Partner().Methods().Load().AllowGroup(GroupAccountManager)
	pool.AccountInvoice().Methods().Load().AllowGroup(GroupAccountUser)
	pool.AccountMoveLine().Methods().Load().AllowGroup(GroupAccountManager)
	pool.AccountMove().Methods().Load().AllowGroup(GroupAccountManager)
	pool.AccountInvoiceTax().Methods().Load().AllowGroup(GroupAccountUser)
	pool.AccountAnalyticLine().Methods().AllowAllToGroup(GroupAccountInvoice)
	pool.AccountInvoiceLine().Methods().Load().AllowGroup(GroupAccountUser)
	pool.AccountAccount().Methods().Load().AllowGroup(GroupAccountInvoice)
	pool.AccountAnalyticAccount().Methods().AllowAllToGroup(GroupAccountUser)
	pool.AccountAccountType().Methods().Load().AllowGroup(GroupAccountInvoice)
	pool.AccountFinancialReport().Methods().AllowAllToGroup(GroupAccountUser)
	pool.AccountFinancialReport().Methods().Load().AllowGroup(GroupAccountInvoice)
	pool.AccountAccountTag().Methods().Load().AllowGroup(GroupAccountUser)
	pool.AccountAccountTag().Methods().Load().AllowGroup(GroupAccountInvoice)
	pool.AccountReconcileModel().Methods().AllowAllToGroup(GroupAccountUser)
	pool.AccountReconcileModelTemplate().Methods().AllowAllToGroup(GroupAccountUser)
	pool.AccountPartialReconcile().Methods().AllowAllToGroup(GroupAccountInvoice)
	pool.AccountPartialReconcile().Methods().AllowAllToGroup(GroupAccountUser)
	pool.AccountFullReconcile().Methods().AllowAllToGroup(GroupAccountInvoice)
	pool.AccountFullReconcile().Methods().AllowAllToGroup(GroupAccountUser)
	pool.AccountPaymentMethod().Methods().AllowAllToGroup(GroupAccountInvoice)
	pool.AccountPayment().Methods().AllowAllToGroup(GroupAccountInvoice)
	pool.AccountBankStatementCashbox().Methods().AllowAllToGroup(GroupAccountUser)
	pool.AccountCashboxLine().Methods().AllowAllToGroup(GroupAccountUser)
	pool.AccountTaxGroup().Methods().Load().AllowGroup(base.GroupUser)
	pool.AccountTaxGroup().Methods().Load().AllowGroup(GroupAccountInvoice)
	pool.AccountTaxGroup().Methods().AllowAllToGroup(GroupAccountManager)
}
